### ISSUE TITLE
Generator creates an empty channel by default - breaks the rendering

### ISSUE THREAD

**Issue by IsmaelMartinez** [event-catalog/generator-eventbridge#23]
### I tried this:

I used the generator to create events that link to a service. 

This generates by default an empty channel. I believe then eventcatalog assumes there is no channel associated, so it doesn't link them together.

### This happened:

Example of the frontmatter generated

```
---
id: id
name: name
version: '1'
schemaPath: name-openapi.json
badges:
  - content: 'Source: name'
    backgroundColor: pink
    textColor: pink
  - content: 'DetailType: undefined'
    backgroundColor: pink
    textColor: pink
  - content: 'Schema name: name'
    backgroundColor: pink
    textColor: pink
channels: [] <----
---
## Overview
```

This then fails to render the "lines" in the graph.

### I expected this:

Expected to render correctly in the UI, and/or to have a 'eventbridge' channel. 

### Is there a workaround?

You can remove the "channels: []" section in each event and then it renders fine.

### EventCatalog Version

2.19.3

### Node.js Version

v22.10.0

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
